// Generated by Website Factory. Update via the factory pipeline, not by hand.

export type Review = {
  author: string;
  rating: number;
  text: string;
  time: string;
};

export type ReviewsData = {
  overallRating: number;
  totalRatings: number;
  reviews: Review[];
};

export const reviewsDataGeneratedFromFactory = true;

export const reviewsData: ReviewsData = {
  "overallRating": 5,
  "totalRatings": 1,
  "reviews": [
    {
      "author": "Caspar Robakowski",
      "rating": 5,
      "text": "Top Qualität",
      "time": "vor 3 Jahren"
    }
  ]
};
